Learning-Fuze/c618_concert_buddy

src/components/new-trip-1/index.js
completed new trip 1 / create trip page functionality with client-server communication and Redux / Redux-Form
=> finished newTrip1 page

.gitignore, public/api/emailInviteFriends.php, src/components/invite/index.js
It should just be the invite file in the php should be minimal changes!
=> Invite emailphp

public/dist/style.css, src/components/invite/input.js
=> fixed styling issue for invite friends input

src/components/invite/index.js
small fix to get array to send
=> fixed email array send

src/components/app.js, src/components/landing/index.js, src/components/login/sign_in.js, src/components/nav/index.js, src/components/planner/index.js
added dynamic auth UI to landing page
=> Landing page auth

public/api/get_responsibilities.php, public/api/toggle_responsibilities.php
Toggle Resp endpoints and fixed true false return
=> Toggle resp

src/actions/index.js
fixed edge case for planner page if users do not have a trip
=> fixed edge case for planner page

public/api/invited.php, src/components/app.js, src/index.js
added whosgoing to be able to pull data
=> Whosgoing invitedand addfriends

src/components/nav/index.js, src/components/team-page/index.js, src/components/team-page/team-page.css
federico, don't touch my component and leave the nav link to "Meet the team"
=> added title to team page for now and need to come up with font themes

src/components/concert-results/concert-results.css, src/components/concert-results/index.js, src/components/responsibility-board/index.js, src/components/responsibility-board/responsibility-board.css
added css for in no responsibilities are found
=> Responsibilities css adjustment

src/components/acceptance-page/index.js, src/components/app.js, src/hoc/redirect.js
=> redirectAccept page done

public/api/accept_invite.php, public/api/invited.php, src/components/acceptance-page/index.js
=> friend successfully added

public/api/accept_invite.php, public/api/emailInviteFriends.php, public/api/invited.php, src/actions/index.js, src/components/acceptance-page/index.js, src/components/app.js, src/components/invite/index.js
fixed populating name of person who invited!
=> Fixing email send

src/components/app.js, src/components/concert-details/index.js, src/components/new-trip-1/index.js
saves concert information and will redirect user so they dont have to  re-search their previous concert
=> New user concert redirect

src/actions/index.js, src/components/planner/index.js, src/reducers/get_user_details_reducer.js
Fixed the planner load when user logs in or creates initial trip
=> fixed loader with check for availble trip & no tripe

src/components/planner/index.js
=> removed extra if statement causing compilation issues

src/components/input.js, src/components/landing/landing.css, src/components/modal/modal.css, src/components/sign-up/sign_up_2.js
=> fixed inputs to customize placeholders

src/components/concert-details/index.js
Finished adding modal to redirect you to planner if you have an exisiting trip!
=> added check for if user currently has a trip

src/actions/index.js, src/actions/types.js, src/components/concert-details/index.js, src/components/login/sign_in.js, src/reducers/user_auth_reducer.js
Fixed issue where invalid login would always display
=> Invalidlogin

public/api/addUser.php, public/api/logout.php, src/actions/index.js, src/components/sign-up/sign_up_2.js
..connected query check result to front end in sign up page
=> Added a query in addUser.php to check if email already exists on user sign up. Also..

public/api/accept_invite.php, public/api/emailInviteFriends.php, src/components/acceptance-page/index.js, src/components/app.js, src/reducers/user_auth_reducer.js
Finished creating unique tokens and checks if user has an existing trip or not
=> Unique tokens per email

public/api/email/accept_invite.php, public/api/handle_login.php, public/api/userlogin/addUser.php
=> just readjusted phpFiles

src/components/planner/index.js
=> fixed loader with a null state

src/components/app.js, src/components/invite/index.js
=> added a delete function from invite input fields

src/components/app.js, src/components/header/index.js, src/components/landing/landing.css, src/components/team-page/team-page.css
added Nav menu to landing page, fixed css styling for landing page and about team media queries
=> Landing page header 

src/components/about/about.css, src/components/login/login.css, src/components/search-concerts/search-concerts.css
added media queries for iPad and iPad Pro for about page and login page
=> About page and login page styling
